package com.philpicinic.easybillsplit.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_GROUP.
 */
public class UserGroup {

    private Long id;
    private String name;

    public UserGroup() {
    }

    public UserGroup(Long id) {
        this.id = id;
    }

    public UserGroup(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
