package com.philpicinic.easybillsplit.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User {

    private Long id;
    private Integer userId;
    private Integer groupId;
    private Integer type;
    private String name;
    private Integer contactId;
    private Integer numberId;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, Integer userId, Integer groupId, Integer type, String name, Integer contactId, Integer numberId) {
        this.id = id;
        this.userId = userId;
        this.groupId = groupId;
        this.type = type;
        this.name = name;
        this.contactId = contactId;
        this.numberId = numberId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getGroupId() {
        return groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getContactId() {
        return contactId;
    }

    public void setContactId(Integer contactId) {
        this.contactId = contactId;
    }

    public Integer getNumberId() {
        return numberId;
    }

    public void setNumberId(Integer numberId) {
        this.numberId = numberId;
    }

}
